name: poultri_sense
description: "Smart Poultry Monitoring Project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1 # Raw StateNotifier API, no generator

  # Navigation
  go_router: ^14.2.0

  # Networking & Data
  mqtt_client: ^10.2.1
  supabase_flutter: ^2.5.8
  shared_preferences: ^2.2.3

  # Hardware & Permissions
  mobile_scanner: ^5.1.1 # Replaces deprecated qr_code_scanner
  permission_handler: ^11.3.1

  # UI & Utilities
  qr_flutter: ^4.1.0
  fl_chart: ^0.68.0
  intl: ^0.19.0 # For DateFormat in formatters
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  


flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/icon_foreground.png
    - assets/images/brand_logo.png

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icon/icon_foreground.png
  android_12:
    color: "#121212"
    image: assets/icon/icon_foreground.png